### PR TITLE
Update Scala to 2.12.16 / 2.13.8 / 3.1.3, Scala Native to 0.4.5, and enable Scala 3 Scala Native support

### PR DESCRIPTION
**Pull request by alexarchambault**
I'd be ok to split in several commits or PRs if needed... (Merging some Scala Steward prior to this one would work too, I'll just rebase.)

### CODE REVIEW

**Comment by kiendang** [comment]
Thanks for this @alexarchambault. I remember trying ScalaPy with a newer version of Scala Native and got error with every version > 0.4.0 when inside virtualenv which is not included in CI here. If I remember correctly it's probably because adding support for virtualenv in #200 requires WString and it interferes with wchar_t* which was added in Scala Native after 0.4.0?

So if you can test python-native-libs inside a virtualenv with your local version of ScalaPy with the bumped dependences that would be great., but later we probably should add tests for virualenv to CI here.

Fastest way you can test is to run this one inside a virtualenv in Ammonite

```scala
import $ivy.`ai.kien::python-native-libs:0.2.2`
import $ivy.`me.shadaj::scalapy-core:<your_local_scalapy_version>`

import ai.kien.python.Python

Python("/usr/bin/python3").scalapyProperties.fold(
  ex => println(s"Error while getting ScalaPy properties: $ex"),
  props => props.foreach { case(k, v) => System.setProperty(k, v) }
)

import me.shadaj.scalapy.py

println(py.module("sys").version)
```

**Comment by kiendang** [comment]
Fastest way to check the above is to run with `python-native-libs`, so create a virtualenv then activate it and run this inside Ammonite

```scala
import $ivy.`ai.kien::python-native-libs:0.2.2`
import $ivy.`me.shadaj::scalapy-core:<your_local_scalapy_version>`

import ai.kien.python.Python

Python("/usr/bin/python3").scalapyProperties.fold(
  ex => println(s"Error while getting ScalaPy properties: $ex"),
  props => props.foreach { case(k, v) => System.setProperty(k, v) }
)

import me.shadaj.scalapy.py

println(py.module("sys").executable)
```
then check if `println(py.module("sys").executable)` print out the correct path to the virtualenv Python executable.

Sorry I'm not with my own computer right now so can't check myself, will take a closer look later.

**Comment by kiendang** [comment]
Ok so I think the fastest way to test this is to create a minimal ScalaPy project with Scala Native, create a virtualenv and then run

```sh
export SCALAPY_PYTHON_PROGRAMNAME=path/to/your/virtualenv/Python/executable
sbt run
```

the ScalaPy code inside the project can just be `println(py.module("sys").executable)` to check if it prints out the correct path to the virtualenv Python executable.

Sorry I'm not with my own computer right now so cannot check this myself. Will take a closer look when I can.

**Review by shadaj — APPROVED** [review]
Code changes look great! I think we'll wait for @kiendang to take a look at Scala Native + Virtualenv support first though before merging.

**Comment by kiendang** [comment]
Just check locally and everything works fine 👍

**Pull request merged**
